### PR TITLE
Fix extra profile setup causing too big transaction

### PR DESCRIPTION
**Pull request by laulaz**
Error was: `TypeError: Can't pickle objects in acquisition wrappers`

### CODE REVIEW

**Comment by mpeeters** [comment]
@laulaz can you please a changelog entry ?

**Comment by laulaz** [comment]
@mpeeters there was nothing in CHANGES since 3 years (hundred of commits, even big changes).

I can add one, but it seems odd after all this work without any ...

**Comment by mpeeters** [comment]
@laulaz yes please add a changelog entry, this will be the case for any new dev from now on

**Comment by laulaz** [comment]
@mpeeters done 👍

**Review by mpeeters — APPROVED** [review]

**Pull request merged**
